name: Test optimize_image_gpt
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  optimized:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      id: optimized_gpt
      with:
        base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v2.2.1/ubuntu-24.04-preinstalled-server-arm64-orangepi-5.img.xz
        optimize_image: yes
        commands: |
            cat /dev/random > /rand || rm /rand
    - name: Check image
      id: compress
      run: |
         parted --script ${{ steps.optimized_gpt.outputs.image }} print free | tail -n2 | head -n1 | grep -c "boot, esp"

